export const layout: string;
export const appSider: string;
export const header: string;
export const logo: string;
export const collapseSider: string;
export const appHeader: string;
export const siderTrigger: string;
export const nav: string;
export const avatarInfo: string;
